/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "messages": {
        "messages": {
            "SUCCESS": {
                "GENERIC": string;
            };
            "ERROR": {
                "VALIDATION_FAILED": string;
                "JSON_SYNTAX_ERROR": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
